name: Deploy Next.js app

on:
  push:
    branches: [master]
  schedule:
    - cron: '28 18 * * *' # 3:28 AM JST every day

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn

      - run: yarn

      - run: yarn build
        # env:
        #   URL_PREFIX: team-blog-hub

      - run: yarn export

      - name: Copy CNAME
        run: cp CNAME out/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
